name: "compress-osk"

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Zipping tools
              run: |
                sudo apt-get update
                sudo apt-get install zip
            
            - name: Create OSK file
              run: |
                zip 'skin.osz' *

            - name: publish
              uses: actions/upload-artifact@v4
              with:
                name: 'skin.osz'
                path: 'skin.osz'

            - name: release
              uses: softprops/action-gh-release@v2
              with:
                files: './skin.osk'
