name: "compress-osk"

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Zipping tools
              run: |
                sudo apt-get update
                sudo apt-get install zip
            
            - name: Create OSK file
              run: |
                zip 'skin.osz' *

            - name: publish
              uses: actions/upload-artifact@v4
              with:
                name: '# a r i s u - astro angelfish edit.osz'
                path: 'skin.osz'

            - name: release
              id: release
              uses: elgohr/Github-Release-Action@v5
              with:
                title: ${{ github.ref }}
                tag: ${{ github.ref }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            - name: release assets
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
              with:
                upload_url: ${{ steps.release.outputs.upload_url }}
                asset_path: ./skin.osz
                asset_name: skin.osz
                asset_content_type: application/zip