name: "compress-osk"

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Zipping tools
              run: |
                sudo apt-get update
                sudo apt-get install zip
            
            - name: Create OSK file
              run: |
                zip 'skin.osz' *

            - name: publish
              uses: actions/upload-artifact@v4
              with:
                name: '# a r i s u - astro angelfish edit.osz'
                path: 'skin.osz'

            - name: release
              uses: ChanTsune/release-with-commit@v2.8.0
              with:
                tag_name: ${{ github.sha }}
                release_name: Release ${{ github.sha }}
                body: |
                  Automated release. please feel free to dig in because i'm lazy for writing them.
                draft: false
                prerelease: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
